# Generated by Django 5.0.2 on 2025-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='listing_type',
            field=models.CharField(choices=[('user', 'User'), ('dealer', 'Dealer')], default='user', max_length=10),
        ),
    ]
