# Generated by Django 5.0.2 on 2025-06-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_has_premium_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='listing_type',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=10),
        ),
    ]
