# Generated by Django 5.0.2 on 2025-05-28 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('reconditioned', 'Reconditioned')], max_length=20)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('registered', models.DateField()),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('semi_auto', 'Semi-Automatic')], max_length=20, null=True)),
                ('exterior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('interior_color', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('air_condition', models.BooleanField(default=False)),
                ('power_windows', models.BooleanField(default=False)),
                ('power_mirrors', models.BooleanField(default=False)),
                ('power_seats', models.BooleanField(default=False)),
                ('power_steering', models.BooleanField(default=False)),
                ('sun_roof', models.BooleanField(default=False)),
                ('abs', models.BooleanField(default=False)),
                ('led', models.BooleanField(default=False)),
                ('reverse_camera', models.BooleanField(default=False)),
                ('air_bags', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.vehicle')),
            ],
        ),
    ]
