# Generated by Django 5.0.2 on 2025-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registered',
            field=models.IntegerField(),
        ),
    ]
