# Generated by Django 5.0.2 on 2025-06-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_vehiclead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at']},
        ),
    ]
