# Generated by Django 5.0.2 on 2025-06-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your contact number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter your WhatsApp number', max_length=15, null=True),
        ),
    ]
