# Generated by Django 5.0.2 on 2025-06-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_vehicle_phone_number_vehicle_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='phone_number',
            field=models.CharField(default='+94', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='whatsapp_number',
            field=models.CharField(default='+94', max_length=15),
        ),
    ]
