# Generated by Django 5.0.2 on 2025-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_vehicle_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('auto', 'Auto'), ('manual', 'Manual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
