# Generated by Django 5.0.2 on 2025-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_vehicle_description_alter_vehicle_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
