# Generated by Django 5.0.2 on 2025-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('brand_new', 'Brand New'), ('used', 'Used (Registered)'), ('recondition', 'Recondition (Unregistered)')], max_length=20),
        ),
    ]
