# Generated by Django 5.0.2 on 2025-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_vehicle_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ad_id',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True),
        ),
    ]
