# Generated by Django 5.0.2 on 2025-06-16 18:54

import ads.models
from django.db import migrations, models
import random
import string

def generate_ad_id():
    # Generate a random 6-digit number
    digits = ''.join(random.choices(string.digits, k=6))
    return f'A{digits}'

def add_ad_ids(apps, schema_editor):
    Vehicle = apps.get_model('ads', 'Vehicle')
    used_ids = set()
    
    for vehicle in Vehicle.objects.all():
        if not vehicle.ad_id:  # Only generate for vehicles without an ad_id
            while True:
                new_id = generate_ad_id()
                if new_id not in used_ids:
                    vehicle.ad_id = new_id
                    used_ids.add(new_id)
                    vehicle.save()
                    break

class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_vehicle_ad_id'),
    ]

    operations = [
        migrations.RunPython(add_ad_ids),
        migrations.AlterField(
            model_name='vehicle',
            name='ad_id',
            field=models.CharField(max_length=7, unique=True, default=generate_ad_id),
        ),
    ]
