# Generated by Django 5.0.2 on 2025-06-16 19:25

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_alter_vehicle_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='boost_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='urgent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ad_id',
            field=models.CharField(default=ads.models.generate_ad_id, max_length=7, unique=True),
        ),
    ]
