# Generated by Django 5.0.2 on 2025-06-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_vehicle_boost_end_date_vehicle_is_boosted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='ad_id',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
