# Generated by Django 5.0.2 on 2025-06-17 17:30

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_alter_vehicle_ad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='boost_end_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_boosted',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_urgent',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='urgent_end_date',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ad_id',
            field=models.CharField(default=ads.models.generate_ad_id, max_length=7, unique=True),
        ),
    ]
