# Generated by Django 5.0.2 on 2025-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_remove_vehicle_boost_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
