# Generated by Django 5.0.2 on 2025-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_vehicle_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=255, unique=True),
        ),
    ]
