# Generated by Django 5.0.2 on 2025-07-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_vehicle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='boost_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
    ]
