# Generated by Django 5.0.2 on 2025-07-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_vehicle_boost_end_date_vehicle_is_boosted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='urgent_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
